repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: mixed-line-ending
        args: [--fix, lf]
      - id: no-commit-to-branch
        stages: [pre-commit, pre-push]
        args: [--branch, master, --branch, devtest-development]
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        name: "ruff lint"
        args: [--fix]
      - id: ruff-format
        name: "ruff format"
  - repo: local
    hooks:
      - id: tests
        name: run unit tests
        entry: make test
        language: python
        types: [python]
        stages: [pre-push]
